num_cores_per_subject: 1

num_subjects_at_once: 2

output_directory: /tmp/output

working_directory: /tmp/workdir

write_all_outputs: False

write_report: True

start_idx: 0

stop_idx: None

slice_timing_correction: False
